language: java
jdk: oraclejdk1.8
script: mvn-e verify
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
     - groma_92@mail.ru
    on_failure: always
    on_success: change